export const COMBINE_STATUS = {
  'inactive/inactive': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Gửi Phiếu',
  },
  'inactive/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Gửi Phiếu',
  },
  'active/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Đăng bán',
  },
  'null/null': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Đăng bán',
  },
  'inactive/pending_for_review': {
    publish_status: 'inactive',
    color: 'red',
    buttonText: 'Hủy duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/pending_for_review': {
    publish_status: 'inactive',
    color: 'red',
    buttonText: 'Hủy duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/active': {
    publish_status: 'inactive',
    color: 'red',
    // buttonText: 'Hủy duyệt',
    colorLabel: 'greenMedium',
    label: 'Đã duyệt',
  },
  'inactive/rejected': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    buttonText: 'Đăng bán',
    colorLabel: 'redPrimary',
    label: 'Bị từ chối',
  },
};

export const COMBINE_STATUS_CHIEF = {
  'inactive/inactive': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'inactive/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'active/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'null/null': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'inactive/pending_for_review': {
    publish_status: 'active',
    status: 'active',
    color: 'red',
    buttonText: 'Duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/pending_for_review': {
    publish_status: 'active',
    status: 'active',
    color: 'red',
    buttonText: 'Duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/active': {
    publish_status: 'inactive',
    color: 'red',
    // buttonText: 'Hủy duyệt',
    colorLabel: 'greenMedium',
    label: 'Đã duyệt',
  },
  'inactive/rejected': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    buttonText: 'Đăng ',
    colorLabel: 'redPrimary',
    label: 'Bị từ chối',
  },
};

export const ORDER_SUPPLIER_FULFILLMENT_STATUS = {
  PENDING: { id: 'pending', name: 'Đang chờ', color: 'grayBlue' },
  SELLER_CONFIRM: {
    id: 'seller_confirm',
    name: 'Chờ Seller xác nhận  ',
    color: 'grayBlue',
  },
  SELLER_CONFIRMED: {
    id: 'seller_confirmed',
    name: 'Chờ NCC xác nhận',
    color: 'grayBlue',
  },
  SELLER_IGNORED: {
    id: 'seller_ignored',
    name: 'Đã hủy',
    color: '#8D8D8D',
  },
  SELLER_CANCELLED: {
    id: 'seller_cancelled',
    name: 'Đã hủy',
    color: '#8D8D8D',
  },
  SUPPLIER_CONFIRM: {
    id: 'supplier_confirm',
    name: 'Chờ NCC xác nhận',
    color: 'grayBlue',
  },
  SUPPLIER_CONFIRMED: {
    id: 'supplier_confirmed',
    name: 'Chờ NCC đóng gói',
    color: 'grayBlue',
  },
  SUPPLIER_PACKED: {
    id: 'supplier_packed',
    name: 'Đã đóng hàng',
    color: 'grayBlue',
  },
  SELLER_DELIVERED: {
    id: 'seller_delivered',
    name: 'seller đã nhận hàng',
    color: 'greenMedium1',
  },
  PLATFORM_DELIVERED: {
    id: 'platform_delivered',
    name: 'Đã giao vận chuyển',
    color: 'greenMedium1',
  },
  PLATFORM_CANCELLED: {
    id: 'platform_cancelled',
    name: 'Kênh bán huỷ',
    color: '#8D8D8D',
  },
  SUPPLIER_DELIVERED: {
    id: 'supplier_delivered',
    name: 'Đã giao vận chuyển',
    color: 'greenMedium1',
  },
  READY_TO_SHIP: {
    id: 'ready_to_ship',
    name: 'Sẵn sàng giao',
    color: 'greenMedium1',
  },
  SUP_REJECTED: {
    id: 'sup_rejected',
    name: 'Đã hủy',
    color: '#8D8D8D',
  },
  SUP_CANCELLED: {
    id: 'sup_cancelled',
    name: 'Đã hủy',
    color: '#8D8D8D',
  },
  BUYER_CANCELLED: {
    id: 'buyer_cancelled',
    name: 'Người mua huỷ',
    color: 'secondary2',
  },
  COMPLETED: { id: 'completed', name: 'Đã giao hàng', color: 'greenMedium1' },
  FULFILLED: { id: 'fulfilled', name: 'Hoàn thành', color: 'greenMedium1' },
  CANCEL: { id: 'cancel', name: 'Đã hủy', color: '#8D8D8D' },
};
