export const COMBINE_STATUS = {
  'inactive/inactive': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Gửi Phiếu',
  },
  'inactive/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Gửi Phiếu',
  },
  'active/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Đăng bán',
  },
  'null/null': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
    buttonText: 'Đăng bán',
  },
  'inactive/pending_for_review': {
    publish_status: 'inactive',
    color: 'red',
    buttonText: 'Hủy gửi duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/pending_for_review': {
    publish_status: 'inactive',
    color: 'red',
    buttonText: 'Hủy gửi duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/active': {
    publish_status: 'inactive',
    color: 'red',
    // buttonText: 'Hủy duyệt',
    colorLabel: 'greenMedium',
    label: 'Đã duyệt',
  },
  'inactive/rejected': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    buttonText: 'Đăng bán',
    colorLabel: 'redPrimary',
    label: 'Bị từ chối',
  },
};

export const COMBINE_STATUS_CHIEF = {
  'inactive/inactive': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'inactive/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'active/draft': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'null/null': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    label: 'Đang nháp',
    colorLabel: '#000',
  },
  'inactive/pending_for_review': {
    publish_status: 'active',
    status: 'active',
    color: 'red',
    buttonText: 'Duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/pending_for_review': {
    publish_status: 'active',
    status: 'active',
    color: 'red',
    buttonText: 'Duyệt',
    colorLabel: '#ff9877',
    label: 'Chờ duyệt',
  },
  'active/active': {
    publish_status: 'inactive',
    color: 'red',
    // buttonText: 'Hủy duyệt',
    colorLabel: 'greenMedium',
    label: 'Đã duyệt',
  },
  'inactive/rejected': {
    publish_status: 'pending_for_review',
    color: 'blue',
    width: '130px',
    buttonText: 'Đăng ',
    colorLabel: 'redPrimary',
    label: 'Bị từ chối',
  },
};

export const RECALL_TIME = 16;
